src/Movie/MovieBundle/Entity/Movie.php
<?php

namespace Movie\MovieBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Movie
 * @package Movie\MovieBundle\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="movie")
 */

class Movie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $title;

    /**
     * @ORM\Column(type="string", length=50)
     */
    protected $director;

    /**
     * @ORM\Column(type="string", length=400)
     */
    protected $summary;

    /**
     * @return mixed
     */
    public function getDirector()
    {
        return $this->director;
    }

    /**
     * @param mixed $director
     */
    public function setDirector($director)
    {
        $this->director = $director;
    }

    /**
     * @return mixed
     */
    public function getRunningTime()
    {
        return $this->running_time;
    }

    /**
     * @param mixed $running_time
     */
    public function setRunningTime($running_time)
    {
        $this->running_time = $running_time;
    }

    /**
     * @return mixed
     */
    public function getActors()
    {
        return $this->actors;
    }

    /**
     * @param mixed $actors
     */
    public function setActors($actors)
    {
        $this->actors = $actors;
    }

    /**
     * @ORM\Column(type="string")
     */
    protected $actors;

    /**
     * @ORM\Column(type="integer")
     */
    protected $running_time;


    /**
     * @ORM\Column(type="decimal", nullable=TRUE, scale=1, precision=3)
     */
    protected $rating;

    /**
     * @ORM\Column(type="string", nullable=TRUE)
     */
    protected $image_file;

    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->image_file;
    }

    /**
     * @param mixed $image_file
     */
    public function setImageFile($image_file)
    {
        $this->image_file = $image_file;
    }


    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * @param mixed $summary
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
    }


    /**
     * @return mixed
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param mixed $rating
     */
    public function setRating($rating)
    {
        $this->rating = $rating;
    }

    /**
     * @ORM\OneToMany(targetEntity="Review", mappedBy="movie")
     */
    private $reviews;

    /**
     * @return ArrayCollection
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    /**
     * @param ArrayCollection $reviews
     */
    public function setReviews($reviews)
    {
        $this->reviews = $reviews;
    }

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function addReview(Review $review)
    {
        $this->reviews[] = $review;
    }




}

src/Movie/MovieBundle/Resources/views/Page/about.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}About{% endblock %}
{% block sidebar %}

{% endblock %}
{% block body %}
    <header>
        <h1>About Movie Rater</h1>
    </header>
    <article>
        <p>
            This movie rating website was developed by Michael Blair
        </p>
        <p>
            If you would like a website dsigned, feel free to contact me on <a href="/">m.blair2@edu.salford.ac.uk</a>
        </p>
    </article>

    <button class="btn btn-warning"><a href="/">Go back</a>
    </button>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/delete.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}Delete Movie{% endblock%}
{% block body %}
    <header>
        <h1>Delete Movie From Database</h1>
    </header>



    <button class="btn btn-danger"><a href="{{ path('movie_index') }}">Cancel Adding Movie</a></button>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/editMovie.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}Edit Movie{% endblock %}
{% block sidebar %}
    <div class="container-fluid">
        {% if movie.imageFile %}
            <img src="{{ asset('uploads/images/') ~ movie.imageFile }}" alt="Movie Poster"/>
        {% else %}
            {% image '@MovieMovieBundle/Resources/Images/image_2.jpg' %}
                <img src="{{ asset_url }}" class="img-fluid" style="width: 100%" alt="Movie image"/>
            {% endimage %}
        {% endif %}
    </div>
{% endblock %}
{% block body %}
    <header>
        <h1>Edit {{ movie.title }}</h1>
    </header>
    <div class="form-group mt-3">
        <form action="" method="post">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </form>
    </div>
    {# TODO add in a confirm #}

    <div class="btn-toolbar">
        <button class="btn btn-danger"><a href="{{ path('movie_index') }}">Cancel Editing Movie</a></button>
    </div>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/index.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block body %}
    <h1>Mickey's Movie Rater Homepage</h1>
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <button class="btn btn-info pull-right"><a href="{{ path('movie_new') }}">Add new movie</a></button>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') %}
        Logged in as: Administrator
    {% elseif is_granted('ROLE_USER') %}
        Logged in as: User
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <p>Username: {{ app.user.username }}</p>
        {% endif %}
    {% else %}
        Anonymous
    {% endif %}
    <hr>
    {% if movies %}
        <table class="table table-striped table-bordered" id="movies">
            <thead>
            <tr>
                <th class="text-center">ID</th>
                <th class="text-center">Title</th>
                <th class="text-center">Director</th>
                <th class="text-center">Actors</th>
                <th class="text-center" colspan="3">Synopsis</th>
                <th class="text-center">Running Time (in minutes)</th>
                <th class="text-center">Rating</th>
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <th colspan="2" class="text-center">Actions</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        {{ movie.id }}
                    </td>
                    <td>
                        <a href="{{ path('movie_view', {'id': movie.id}) }}">{{ movie.title }}</a>
                    </td>
                    <td>
                        {{ movie.director }}
                    </td>
                    <td>
                        {{ movie.actors }}
                    </td>
                    <td colspan="3">
                        {{ movie.summary }}
                    </td>
                    <td>
                        {{ movie.runningTime }}
                    </td>
                    <td>
                        {{ movie.rating }}
                    </td>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <td>

                        <a href="{{ path('movie_edit', {'id': movie.id}) }}" class="btn btn-outline-primary"
                           data-id="{{ movie.id }}">Edit</a>
                    </td>
                    {% if is_granted('ROLE_ADMIN') %}
                        <td>
                            <a href="#" class="btn btn-danger delete-movie" data-id="{{ movie.id }}">Delete</a>
                        </td>
                    {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {# display navigation #}
        <div class="navigation text-center">
            {{ knp_pagination_render(movies) }}
        </div>

    {% else %}
        <p>No movies to show</p>
    {% endif %}
{% endblock %}

{% block sidebar %}
    <h2>New Releases</h2>
    <div>Check out the movies below which have recently been added to our database!</div>
    <br>
    {# Rendering controllers i templates is not working #}
    {# <div>{{ render(controller( #}
    {# 'Movie\MovieBundle\Controller\PageController::newReleaseAction' #}
    {# )) }}</div> #}
    <div class="list-group">
        {% for release in releases %}
            <a href="{{ path('movie_view', {'id': release.id}) }}"
               class="list-group-item list-group-item-success text-center">{{ release.title }}</a>
            <br><br>
        {% endfor %}
    </div>
{% endblock %}

{# {% block javascripts %} #}
{# {% javascripts '@MovieMovieBundle/Resources/js/main.js' %} #}
{# <script src="{{ asset_url }}"></script> #}
{# {% endjavascripts %} #}
{# {% endblock %} #}

src/Movie/MovieBundle/Resources/views/Page/movie.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}{{ movie.title }} {% endblock %}
{% block sidebar %}
    <div class="container-fluid mt-3">
        {% if movie.imageFile %}
            <img src="{{ asset('uploads/images/') ~ movie.imageFile }}" class="img-fluid uploaded-image"
                 alt="Movie Poster"/>
        {% else %}
            {% image '@MovieMovieBundle/Resources/Images/image_2.jpg' %}
                <img src="{{ asset_url }}" style="width: 100%" class="uploaded-image" alt="Stock Movie image"/>
            {% endimage %}
        {% endif %}
    </div>
    <div class="mt-3">
        <h2 class="display-4 text-info">Director:</h2>
        <h2 class="text-muted"> {{ movie.director }}</h2>
        <h2 class="display-4 text-info">Actors:</h2>
        <h2 class="text-muted"> {{ movie.actors }}</h2>
        <h2 class="display-4 text-info">Running Time:</h2>
        <h2 class="text-muted"> {{ movie.runningTime }}</h2>
        <h2 class="display-4 text-info">Storyline:</h2>
        <p>{{ movie.summary }}</p>
    </div>
{% endblock %}
{% block body %}
    <div class="mt-3">
        <h2 class="display-7 text-info">Movie ID: {{ movie.id }}</h2>
        <h2 class="display-4 text-info">Title: {{ movie.title }}</h2>
        <h2 class="display-4 text-info">Rating: {{ movie.rating }}</h2>
    </div>
    <hr>
    <br>
    <div>
        <h1>Reviews</h1>
        <button class="btn btn-info pull-right mb-3"><a href="{{ path('review_create',{'id': movie.id} ) }}">Add
                review</a>
        </button>
        {% if reviews %}
            <table class="table table-striped table-bordered border-3">
                <thead>
                <tr>
                    <th>Review_ID</th>
                    <th>Review</th>
                    <th>Reviewer_ID</th>
                    <th>Rating</th>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <th colspan="2">Actions</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for review in reviews %}
                    <tr>
                        <td>
                            <a
                                    href="{{ path('review_view',{'id': review.id} ) }}">{{ review.id }}</a>
                        </td>
                        <td>
                            <a
                                    href="{{ path('review_view',{'id': review.id} ) }}">{{ review.review }}</a>
                        </td>
                        <td>
                            {{ review.reviewer.id }}
                        </td>
                        <td>
                            {{ review.rating }}
                        </td>
                        <td>
                            {# if current user is the owner of this record, they can edit the review #}
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                {% if app.user.id == review.reviewer.id %}
                                    <button class="btb btn-dark"><a
                                                href="{{ path('review_edit',{'id': review.id} ) }}">Edit</a>
                                    </button>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

{#            display navigation#}
            <div class="navigation text-center">
                {{ knp_pagination_render(reviews) }}
            </div>
        {% else %}
            <p>No reviews to show</p>
        {% endif %}

    </div>
    <div class="btn-toolbar">
        <button class="btn btn-warning"><a href="/">Go back</a>
        </button>
    </div>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/new.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}Add Movie{% endblock %}
{% block sidebar %}

{% endblock %}
{% block body %}
    <header>
        <h1>Add Movie To Database</h1>
    </header>
    <div class="form-group mt-3">
        <form action="" method="post" enctype="multipart/form-data">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </form>
        {# TODO add in a confirm #}
    </div>
    <div class="btn-toolbar">
        <button type="button" class="btn btn-danger"><a href="{{ path('movie_index') }}">Cancel Adding Movie</a>
        </button>
    </div>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/newreview.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}Add review {% endblock%}
{% block body %}
    <header>
        <h1>Add review for MOVIE_TITLE</h1>
    </header>
    <form action="" method="post">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </form>

{#    Cannot get the path to come back to the show page for specific movie so just going back to index for now#}
    <button class="btn btn-danger"><a href="{{ path('movie_index') }}">Cancel Adding Review</a></button>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/search.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %} Search Results {% endblock %}
{% block sidebar %}
{% endblock %}
{% block body %}
    {% if query %}
        <h1> Search Results for "{{ query }}"</h1>
    {% endif %}
    {% if movies %}
        <table class="table table-striped table-bordered" id="movies">
            <thead>
            <tr>
                <th class="text-center">ID</th>
                <th class="text-center">Title</th>
                <th class="text-center">Director</th>
                <th class="text-center">Actors</th>
                <th class="text-center" colspan="3">Synopsis</th>
                <th class="text-center">Running Time (in minutes)</th>
                <th class="text-center">Rating</th>
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <th colspan="2" class="text-center">Actions</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        {{ movie.id }}
                    </td>
                    <td>
                        <a href="{{ path('movie_show', {'id': movie.id}) }}">{{ movie.title }}</a>
                    </td>
                    <td>
                        {{ movie.director }}
                    </td>
                    <td>
                        {{ movie.actors }}
                    </td>
                    <td colspan="3">
                        {{ movie.summary }}
                    </td>
                    <td>
                        {{ movie.runningTime }}
                    </td>
                    <td>
                        {{ movie.rating }}
                    </td>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <td>

                            <a href="{{ path('movie_edit', {'id': movie.id}) }}" class="btn btn-outline-primary"
                               data-id="{{ movie.id }}">Edit</a>
                        </td>
                        {% if is_granted('ROLE_ADMIN') %}
                            <td>
                                <a href="#" class="btn btn-danger delete-movie" data-id="{{ movie.id }}">Delete</a>
                            </td>
                        {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {# display navigation #}
        <div class="navigation text-center">
            {{ knp_pagination_render(movies) }}
        </div>

    {% else %}
        <p>No movies to show</p>
    {% endif %}
    {# <form action="" method="post"> #}
    {# {{ form_start(form) }} #}
    {# {{ form_widget(form) }} #}
    {# {{ form_end(form) }} #}
    {# </form> #}

    {# <form action="" method="post"> #}
    {# {{ form_start(form, { #}
    {# 'attr': {'class': 'navbar-form navbar-right'} #}
    {# }) }} #}

    {# {{ form_widget(form.search, { #}
    {# 'attr': {'class': 'form-control search-query'} }) }} #}


    {# {{ form_end(form) }} #}
    {# </form> #}
    {# <h1>ID: {{ movie.id }}</h1> #}
    {# <h1>Title: {{ movie.title }}</h1> #}
    {# <h1>Rating: {{ movie.rating }}</h1> #}
    {# <h2>Storyline</h2> #}
    {# <p>{{ movie.summary }}</p> #}
    {# <hr> #}
    {# <div class="container-fluid"> #}
    {# {% image '@MovieMovieBundle/Resources/Images/image_2.jpg' %} #}
    {# <img src="{{ asset_url }}" class="img-fluid" style="width: 100%" alt="Movie image"/> #}
    {# {% endimage %} #}
    {# </div> #}
    {# <hr> #}
    {# <div> #}
    {# <h1>Search Results</h1> #}
    {# {% if results %} #}
    {# <table class="table table-striped table-bordered"> #}
    {# <thead> #}
    {# <tr> #}
    {# <th>Review_ID</th> #}
    {# <th>Review</th> #}
    {# <th>Reviewer_ID</th> #}
    {# <th>Rating</th> #}
    {# {% if is_granted('IS_AUTHENTICATED_FULLY') %} #}
    {# <th colspan="2">Actions</th> #}
    {# {% endif %} #}
    {# </tr> #}
    {# </thead> #}
    {# <tbody> #}
    {# {% for result in results %} #}
    {# <tr> #}
    {# <td> #}
    {# {{ result.review.id }} #}
    {# </td> #}
    {# <td> #}
    {# {{ result.review.review }} #}
    {# </td> #}
    {# <td> #}
    {# {{ result.review.reviewer.id }} #}
    {# </td> #}
    {# <td> #}
    {# {{ result.review.rating }} #}
    {# </td> #}
    {# <td> #}
    {# #}{# if current user is the owner of this record, they can edit the review #}
    {# {% if is_granted('IS_AUTHENTICATED_FULLY') %} #}
    {# {% if app.user.id == result.review.reviewer.id %} #}
    {# <button class="btb btn-dark"><a href="{{ path('movie_review_edit',{'id': result.review.id} ) }}">Edit</a></button> #}
    {# {% endif %} #}
    {# {% endif %} #}
    {# </td> #}
    {# </tr> #}
    {# {% endfor %} #}
    {# </tbody> #}
    {# </table> #}
    {# {% else %} #}
    {# <p>No results to show</p> #}
    {# {% endif %} #}

    {# </div> #}
    <a href="/">Go back</a>

{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/show.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}{{ movie.title }} {% endblock %}
{% block sidebar %}
    <div class="container-fluid mt-3">
        {% if movie.imageFile %}
            <img src="{{ asset('uploads/images/') ~ movie.imageFile }}" class="img-fluid uploaded-image"
                 alt="Movie Poster"/>
        {% else %}
            {% image '@MovieMovieBundle/Resources/Images/image_2.jpg' %}
                <img src="{{ asset_url }}" style="width: 100%" class="uploaded-image" alt="Stock Movie image"/>
            {% endimage %}
        {% endif %}
    </div>
    <div class="mt-3">
        <h2 class="display-4 text-info">Director:</h2>
        <h2 class="text-muted"> {{ movie.director }}</h2>
        <h2 class="display-4 text-info">Actors:</h2>
        <h2 class="text-muted"> {{ movie.actors }}</h2>
        <h2 class="display-4 text-info">Running Time:</h2>
        <h2 class="text-muted"> {{ movie.runningTime }}</h2>
        <h2 class="display-4 text-info">Storyline:</h2>
        <p>{{ movie.summary }}</p>
    </div>
{% endblock %}
{% block body %}
    <div class="mt-3">
        <h2 class="display-7 text-info">Movie ID: {{ movie.id }}</h2>
        <h2 class="display-4 text-info">Title: {{ movie.title }}</h2>
        <h2 class="display-4 text-info">Rating: {{ movie.rating }}</h2>
    </div>
    <hr>
    <br>
    <div>
        <h1>Reviews</h1>
        <button class="btn btn-info pull-right mb-3"><a href="{{ path('review_create',{'id': movie.id} ) }}">Add
                review</a>
        </button>
        {% if reviews %}
            <table class="table table-striped table-bordered border-3">
                <thead>
                <tr>
                    <th>Review_ID</th>
                    <th>Review</th>
                    <th>Reviewer_ID</th>
                    <th>Rating</th>
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <th colspan="2">Actions</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for review in reviews %}
                    <tr>
                        <td>
                            {{ review.id }}
                        </td>
                        <td>
                            {{ review.review }}
                        </td>
                        <td>
                            {{ review.reviewer.id }}
                        </td>
                        <td>
                            {{ review.rating }}
                        </td>
                        <td>
                            {# if current user is the owner of this record, they can edit the review #}
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                {% if app.user.id == review.reviewer.id %}
                                    <button class="btb btn-dark"><a
                                                href="{{ path('review_edit',{'id': review.id} ) }}">Edit</a>
                                    </button>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {# display navigation #}
            <div class="navigation text-center">
                {{ knp_pagination_render(reviews) }}
            </div>
        {% else %}
            <p>No reviews to show</p>
        {% endif %}

    </div>
    <div class="btn-toolbar">
        <button class="btn btn-warning"><a href="/">Go back</a>
        </button>
    </div>
{% endblock %}

src/Movie/MovieBundle/Resources/views/Page/userpage.html.twig
{% extends 'MovieMovieBundle::layout.html.twig' %}
{% block title %}{{ app.user.username }} {% endblock %}
{% block sidebar %}
    <h2>UserID: {{ app.user.id }}</h2>
    <h2>Username: {{ app.user.username }}</h2>
    {# TODO add in link to update details form #}
    <h2><a href="/">Update details</a></h2>
{% endblock %}
{% block body %}
    <div>
        <h1>User Details for {{ app.user.username }}</h1>

        {% if reviews %}
            <table id="movies" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Review ID</th>
                    <th>Movie</th>
                    <th>Review</th>
                    <th>Rating</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for review in reviews %}
                    <tr>
                        <td>
                            {{ review.id }}
                        </td>
                        <td>
                            {{ review.movie.title }}
                        </td>

                        <td>
                            {{ review.review }}
                        </td>
                        <td>
                            {{ review.rating }}
                        </td>
                        <td>
                            <a href="{{ path('movie_review_edit', {'id': review.id}) }}">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You have not reviewed any movies yet.</p>
            <p>Select a movie from the <a href="{{ path('movie_index') }}">list</a> and give it a review!</p>
        {% endif %}

    </div>
    <button class="btn btn-warning"><a href="/">Go back</a>
    </button>

{% endblock %}